# Generated by Django 5.1.4 on 2025-02-20 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collaboration_name', models.CharField(max_length=255, verbose_name='Collaboration Title')),
                ('collaboration_description', models.TextField(help_text='Write a Description for your Collaborations', null=True)),
                ('STATUS', models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active'), ('completed', 'Completed'), ('removed', 'Removed')], default='inactive', max_length=10, verbose_name='Collaboration Status')),
                ('collaboration_type', models.CharField(choices=[('freelancer', 'Freelancer Collaboration'), ('client', 'Client Collaboration'), ('mixed', 'Mixed Collaboration'), ('project', 'Project Collaboration')], default='mixed', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_collaborations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CollaborationInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collaboration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='collaborations.collaboration')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CollaborationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('collaborator', 'Collaborator')], max_length=50)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('collaboration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='collaborations.collaboration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaboration_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('collaboration', 'user')},
            },
        ),
    ]
