# Generated by Django 5.1.6 on 2025-03-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collaboration_name', models.CharField(max_length=255, verbose_name='Collaboration Title')),
                ('collaboration_description', models.TextField(help_text='Write a Description for your Collaborations', null=True)),
                ('STATUS', models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active'), ('completed', 'Completed'), ('removed', 'Removed')], default='inactive', max_length=10, verbose_name='Collaboration Status')),
                ('collaboration_type', models.CharField(choices=[('freelancer', 'Freelancer Collaboration'), ('client', 'Client Collaboration'), ('project', 'Project Collaboration'), ('request_job', 'Request Job Collaboration')], default='mixed', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CollaborationInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CollaborationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('collaborator', 'Collaborator')], max_length=50)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
