# Generated by Django 5.1.4 on 2025-02-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_event_description_event_end_alter_event_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(null=True),
        ),
    ]
