# Generated by Django 5.1.4 on 2025-02-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_event_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end',
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateField(null=True),
        ),
    ]
