# Generated by Django 5.1.4 on 2025-02-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_remove_event_description_remove_event_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(blank=True, choices=[('Project', 'Project'), ('Event', 'Event'), ('Meeting', 'Meeting'), ('Deadline', 'Deadline'), ('Others', 'Others')], max_length=100, null=True),
        ),
    ]
