# Generated by Django 5.1.4 on 2025-02-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(blank=True, choices=[('Meeting', 'Meeting'), ('Deadline', 'Deadline'), ('Others', 'Others')], max_length=100, null=True),
        ),
    ]
