# Generated by Django 5.1.4 on 2025-02-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_alter_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='notification_time',
            field=models.PositiveIntegerField(default=1440, help_text='Notification time in minutes before the event.'),
        ),
    ]
