# Generated by Django 5.1.6 on 2025-03-23 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_number', models.PositiveSmallIntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year'), (5, '5th Year'), (6, '6th Year')])),
                ('description', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True, null=True)),
                ('accreditation', models.CharField(blank=True, max_length=255)),
                ('ranking', models.PositiveIntegerField(blank=True, help_text='National ranking if available', null=True)),
                ('established_year', models.PositiveIntegerField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether this institution has been verified by our team')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FieldOfStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields_of_study', to='talentrise.academicdiscipline')),
            ],
            options={
                'verbose_name_plural': 'Fields of Study',
                'unique_together': {('name', 'discipline')},
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('abbreviation', models.CharField(blank=True, max_length=20)),
                ('level', models.CharField(choices=[('diploma', 'Diploma'), ('associate', 'Associate Degree'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('doctoral', 'Doctoral Degree'), ('certificate', 'Certificate Program')], max_length=20)),
                ('duration_years', models.DecimalField(decimal_places=1, help_text='Duration in years', max_digits=3)),
                ('description', models.TextField(blank=True)),
                ('fields_of_study', models.ManyToManyField(related_name='courses', to='talentrise.fieldofstudy')),
            ],
            options={
                'unique_together': {('name', 'level')},
            },
        ),
        migrations.CreateModel(
            name='TalentRiseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduation_year', models.PositiveIntegerField(help_text='Expected graduation year')),
                ('student_id', models.CharField(blank=True, help_text='Official student ID at the institution', max_length=50)),
                ('enrollment_date', models.DateField(blank=True, help_text='When the student enrolled in their program', null=True)),
                ('weekly_availability', models.CharField(choices=[('5-10', '5-10 hours/week'), ('10-15', '10-15 hours/week'), ('15-20', '15-20 hours/week'), ('20+', 'More than 20 hours/week')], default='10-15', max_length=10)),
                ('preferred_work_categories', models.TextField(blank=True, help_text='Areas of work the student is interested in')),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, help_text='Current GPA on a 4.0 scale', max_digits=3, null=True)),
                ('academic_achievements', models.TextField(blank=True, help_text='Honors, awards, scholarships, etc.')),
                ('academic_projects', models.JSONField(blank=True, default=list, help_text='List of academic projects completed or in progress')),
                ('certifications', models.JSONField(blank=True, default=list, help_text='List of relevant certifications')),
                ('is_verified', models.BooleanField(default=False, help_text='Indicates if academic credentials have been verified')),
                ('verification_document', models.FileField(blank=True, help_text='Student ID or enrollment verification document', null=True, upload_to='talentrise_verification/')),
                ('verification_date', models.DateField(blank=True, help_text='When the profile was verified', null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('completed_gigs', models.PositiveIntegerField(default=0)),
                ('ongoing_gigs', models.PositiveIntegerField(default=0)),
                ('profile_completion', models.PositiveSmallIntegerField(default=0, help_text='Profile completion percentage')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the student is currently active in the program')),
                ('current_semester', models.PositiveSmallIntegerField(blank=True, help_text='Current semester of study', null=True)),
                ('academic_status', models.CharField(choices=[('active', 'Active'), ('graduated', 'Graduated'), ('on_break', 'On Break'), ('dropped', 'Dropped')], default='active', help_text='Current academic status of the student', max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='talentrise.course')),
                ('field_of_study', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='talentrise.fieldofstudy')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='talentrise.institution')),
                ('skills', models.ManyToManyField(related_name='talentrise_students', to='core.skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='talentrise_profile', to=settings.AUTH_USER_MODEL)),
                ('year_of_study', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='talentrise.academicyear')),
            ],
            options={
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='TalentRisePortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('academic', 'Academic Project'), ('personal', 'Personal Project'), ('freelance', 'Freelance Work'), ('internship', 'Internship Project'), ('competition', 'Competition Entry')], default='academic', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='talentrise_portfolio/')),
                ('project_url', models.URLField(blank=True, null=True)),
                ('repository_url', models.URLField(blank=True, help_text='GitHub or other repository link', null=True)),
                ('date_created', models.DateField()),
                ('date_completed', models.DateField(blank=True, null=True)),
                ('is_academic', models.BooleanField(default=True, help_text='Indicates if this is an academic project')),
                ('course_related', models.CharField(blank=True, help_text='Course or subject this project was part of', max_length=255)),
                ('grade_received', models.CharField(blank=True, help_text='Grade received for this project if applicable', max_length=10)),
                ('recognition', models.TextField(blank=True, help_text='Any awards or recognition received')),
                ('featured', models.BooleanField(default=False, help_text='Featured projects appear prominently on the profile')),
                ('skills_used', models.ManyToManyField(related_name='portfolio_uses', to='core.skill')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='talentrise.talentriseprofile')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
