# Generated by Django 5.1.4 on 2025-02-20 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userfeedback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Connection',
            new_name='ConnectionRequests',
        ),
    ]
