# Generated by Django 5.1.6 on 2025-03-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_automated_payment',
            field=models.BooleanField(default=False),
        ),
    ]
