# Generated by Django 5.1.4 on 2025-02-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_connection_delete_connectionrequests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('freelancer', 'Freelancer'), ('client', 'Client')], db_index=True, default='freelancer', max_length=20),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['title'], name='core_projec_title_3ad890_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['description'], name='core_projec_descrip_4174cb_idx'),
        ),
    ]
