# Generated by Django 5.1.4 on 2025-02-21 09:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_category_name_alter_project_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='projects_assigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
