# Generated by Django 5.1.4 on 2025-02-21 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_project_assigned_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Messages', 'Messages'), ('Payments', 'Payments'), ('Projects', 'Projects'), ('Connections', 'Connections'), ('System', 'System'), ('Collaborations', 'Collaborations')], max_length=20)),
                ('related_model_id', models.PositiveIntegerField()),
                ('notification_text', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
