# Generated by Django 5.1.4 on 2025-02-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_task_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('Messages', 'Messages'), ('Payments', 'Payments'), ('Projects', 'Projects'), ('Projects & Tasks', 'Projects & Tasks'), ('Connections', 'Connections'), ('System', 'System'), ('Collaborations', 'Collaborations')], max_length=20),
        ),
    ]
