# Generated by Django 5.1.4 on 2025-02-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='membership',
            field=models.CharField(choices=[('free', 'Free'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='free', max_length=10),
        ),
    ]
