# Generated by Django 5.1.4 on 2025-02-23 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_user_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('Messages', 'Messages'), ('Payments', 'Payments'), ('Projects', 'Projects'), ('Events', 'Events'), ('Projects & Tasks', 'Projects & Tasks'), ('Connections', 'Connections'), ('System', 'System'), ('Collaborations', 'Collaborations')], max_length=20),
        ),
    ]
