# Generated by Django 5.1.4 on 2025-02-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('initiated', 'Initiated'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
