# Generated by Django 5.1.6 on 2025-03-10 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_notification_title_alter_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_type', models.CharField(choices=[('combined', 'Combined Budget'), ('individual', 'Individual Budget')], default='individual', max_length=10)),
                ('estimated_duration', models.CharField(max_length=100)),
                ('comments', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('combined_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('media_files', models.FileField(blank=True, null=True, upload_to='bid_media/')),
                ('link', models.URLField(blank=True, null=True)),
                ('task_budgets', models.JSONField(blank=True, default=dict)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='core.project')),
                ('tasks', models.ManyToManyField(related_name='bids', to='core.task')),
            ],
            options={
                'indexes': [models.Index(fields=['freelancer', 'project', 'status'], name='core_bid_freelan_6f7459_idx')],
                'unique_together': {('freelancer', 'project')},
            },
        ),
    ]
