# Generated by Django 5.1.6 on 2025-03-10 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_bid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bid',
        ),
    ]
