# Generated by Django 5.1.6 on 2025-03-23 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profile', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_details', to='Profile.companydetails'),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.department'),
        ),
        migrations.AddField(
            model_name='education',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.course'),
        ),
        migrations.AddField(
            model_name='education',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.department'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='from_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedback',
            name='parent_feedback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='Profile.feedback'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='to_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='addresses',
            field=models.ManyToManyField(related_name='freelancer_addresses', to='Profile.address'),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='bank_details',
            field=models.ManyToManyField(related_name='freelancer_banks', to='Profile.bankdetails'),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='certifications',
            field=models.ManyToManyField(blank=True, related_name='freelancer_certs', to='Profile.certification'),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Profile.companydetails'),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='education',
            field=models.ManyToManyField(blank=True, related_name='freelancer_education', to='Profile.education'),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='freelancer_skills', to='core.skill'),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='freelancerreview',
            name='from_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='freelancerreview',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project'),
        ),
        migrations.AddField(
            model_name='freelancerreview',
            name='to_freelancer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_freelancer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_students', to='Profile.institution'),
        ),
        migrations.AddField(
            model_name='education',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.institution'),
        ),
        migrations.AddField(
            model_name='department',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.institution'),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='portfolio_items',
            field=models.ManyToManyField(blank=True, related_name='freelancer_portfolio', to='Profile.portfolioitem'),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='verification_documents',
            field=models.ManyToManyField(related_name='freelancer_documents', to='Profile.verificationdocument'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='verification_documents',
            field=models.ManyToManyField(blank=True, related_name='client_documents', to='Profile.verificationdocument'),
        ),
    ]
