# Generated by Django 5.1.6 on 2025-03-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='primary_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
