# Generated by Django 5.1.6 on 2025-03-27 11:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_freelancerprofile_primary_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancerprofile',
            name='id_verified',
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='last_verification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='legal_agreements',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='privacy_policy_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='response_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='secondary_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='terms_acceptance_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='addresses',
            field=models.ManyToManyField(blank=True, related_name='freelancer_addresses', to='Profile.address'),
        ),
        migrations.RemoveField(
            model_name='freelancerprofile',
            name='bank_details',
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='freelancer_company', to='Profile.companydetails'),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='verification_documents',
            field=models.ManyToManyField(blank=True, related_name='freelancer_documents', to='Profile.verificationdocument'),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='bank_details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='freelancer_bank', to='Profile.bankdetails'),
        ),
    ]
